services:
  fixdesk:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - /node/FixDesk/backend:/FixDesk
    env_file:
      - ./.env
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    depends_on:
      - fixdesk
    networks:
      - backend

networks:
  backend:
    driver: bridge
