services:
  fixdesk:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - /node/FixDesk/backend:/FixDesk
    env_file:
      - ./.env
    networks:
      - common_network
    container_name: fixdesk_backend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    depends_on:
      - fixdesk
    networks:
      - common_network
    container_name: fixdesk_nginx

networks:
  common_network:
    external: true
    name: common_network