# Generated by Django 4.2.5 on 2023-10-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticketRequester', models.CharField(max_length=30)),
                ('department', models.CharField(blank=True, max_length=10, null=True)),
                ('mail', models.EmailField(max_length=50)),
                ('company', models.CharField(max_length=15)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('sector', models.CharField(max_length=20)),
                ('occurrence', models.CharField(max_length=20)),
                ('problemn', models.CharField(max_length=20)),
                ('observation', models.TextField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('respective_area', models.CharField(max_length=10)),
                ('responsible_technician', models.CharField(blank=True, max_length=30, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PID', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('open', models.BooleanField(default=True)),
                ('chat', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
