# Generated by Django 5.0.3 on 2024-12-10 19:19

import django.db.models.deletion
import helpdesk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticketRequester', models.CharField(max_length=31)),
                ('department', models.CharField(blank=True, max_length=10, null=True)),
                ('mail', models.EmailField(max_length=50)),
                ('company', models.CharField(max_length=15)),
                ('sector', models.CharField(max_length=20)),
                ('occurrence', models.CharField(max_length=20)),
                ('problemn', models.CharField(max_length=20)),
                ('observation', models.TextField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('respective_area', models.CharField(max_length=10)),
                ('responsible_technician', models.CharField(blank=True, max_length=30, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PID', models.IntegerField()),
                ('open', models.BooleanField(null=True)),
                ('chat', models.TextField(blank=True, max_length=10000, null=True)),
                ('equipament', models.TextField(blank=True, max_length=30, null=True)),
                ('date_alocate', models.TextField(blank=True, max_length=1000)),
                ('details', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=helpdesk.models.support_ticket_file_path)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpdesk.supportticket')),
            ],
        ),
    ]
