# Generated by Django 4.2.1 on 2026-08-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'helpdesk_ticketfile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticketRequester', models.CharField(max_length=31)),
                ('department', models.CharField(blank=True, max_length=10, null=True)),
                ('mail', models.EmailField(max_length=50)),
                ('company', models.CharField(max_length=15)),
                ('sector', models.CharField(max_length=20)),
                ('occurrence', models.CharField(max_length=20)),
                ('problemn', models.CharField(max_length=20)),
                ('observation', models.TextField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('respective_area', models.CharField(max_length=10)),
                ('responsible_technician', models.CharField(blank=True, max_length=30, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PID', models.IntegerField()),
                ('chat', models.TextField(blank=True, max_length=10000, null=True)),
                ('equipament', models.TextField(blank=True, max_length=30, null=True)),
                ('date_alocate', models.TextField(blank=True, max_length=1000, null=True)),
                ('open', models.BooleanField(null=True)),
                ('details', models.TextField(blank=True, max_length=1000, null=True)),
                ('last_sender', models.TextField(max_length=31, null=True)),
                ('last_viewer', models.TextField(max_length=10000, null=True)),
                ('technician_mail', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField()),
                ('ticket', models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.PROTECT, to='helpdesk.supportticket')),
            ],
            options={
                'db_table': 'helpdesk_ticketmail',
                'managed': True,
            },
        ),
    ]
