# Generated by Django 5.0.3 on 2024-12-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='date_alocate',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
