# Generated by Django 4.2.1 on 2023-10-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_equipaments_company'),
        ('helpdesk', '0002_remove_supportticket_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='equipament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.equipaments'),
        ),
    ]
