# Generated by Django 4.2.1 on 2026-08-12 15:04

from django.db import migrations, models
import django.db.models.deletion

def migrate_areas(apps, schema_editor):
    Area = apps.get_model('helpdesk', 'Area')
    
    ti_area, _ = Area.objects.get_or_create(code='TI', defaults={'active': True})
    fiscal_area, _ = Area.objects.get_or_create(code='Fiscal', defaults={'active': True})
    
    area_map = {
        'TI': ti_area.id,
        'Fiscal': fiscal_area.id,
    }
    
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, respective_area FROM helpdesk_supportticket")
        rows = cursor.fetchall()
        for row in rows:
            ticket_id, old_area = row
            # Failsafe fallback
            new_area_id = area_map.get(old_area, ti_area.id)
            cursor.execute(
                "UPDATE helpdesk_supportticket SET respective_area = %s WHERE id = %s",
                [new_area_id, ticket_id]
            )

def reverse_migrate_areas(apps, schema_editor):
    Area = apps.get_model('helpdesk', 'Area')
    area_map = {area.id: area.code for area in Area.objects.all()}
    
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, respective_area FROM helpdesk_supportticket")
        rows = cursor.fetchall()
        for row in rows:
            ticket_id, area_id = row
            try:
                area_id_int = int(area_id)
                old_code = area_map.get(area_id_int, 'TI')
            except (ValueError, TypeError):
                old_code = 'TI'
                
            cursor.execute(
                "UPDATE helpdesk_supportticket SET respective_area = %s WHERE id = %s",
                [old_code, ticket_id]
            )

class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_create_fiscal_technician_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'helpdesk_area',
                'managed': True,
            },
        ),
        migrations.RunPython(migrate_areas, reverse_migrate_areas),
        migrations.AlterField(
            model_name='supportticket',
            name='respective_area',
            field=models.ForeignKey(db_column='respective_area', on_delete=django.db.models.deletion.PROTECT, to='helpdesk.area'),
        ),
    ]
