# Generated by Django 4.2.1 on 2023-10-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_supportticket_equipament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days_Alocated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='supportticket',
            name='date_alocate',
            field=models.ManyToManyField(to='helpdesk.days_alocated'),
        ),
    ]
