# Generated by Django 4.2.1 on 2023-10-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_days_alocated_supportticket_date_alocate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='date_alocate',
        ),
        migrations.DeleteModel(
            name='Days_Alocated',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='date_alocate',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
