# Generated by Django 4.2.1 on 2023-10-30 16:36

from django.db import migrations, models
import helpdesk.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_remove_supportticket_date_alocate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=helpdesk.models.support_ticket_file_path),
        ),
    ]
