# Generated by Django 4.2.1 on 2023-11-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_supportticket_company_new_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='sector_new_user',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
