# Generated by Django 4.2.1 on 2023-11-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_supportticket_sector_new_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='start_work_new_user',
            field=models.TextField(blank=True, max_length=60),
        ),
    ]
