# Generated by Django 4.2.1 on 2023-11-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_alter_supportticket_start_work_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='mail_tranfer',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='old_files',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
