# Generated by Django 4.2.1 on 2023-11-22 17:29

from django.db import migrations, models
import django.db.models.deletion
import helpdesk.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_supportticket_mail_tranfer_supportticket_old_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='file',
        ),
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=helpdesk.models.support_ticket_file_path)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.supportticket')),
            ],
        ),
    ]
