# Generated by Django 4.2.1 on 2023-12-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0012_alter_ticketfile_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='machine_new_user',
            field=models.BooleanField(blank=True),
        ),
    ]
