# Generated by Django 4.2.1 on 2023-12-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_alter_supportticket_machine_new_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='machine_new_user',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
