# Generated by Django 5.0.3 on 2024-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0014_alter_supportticket_machine_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='equipament',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='open',
            field=models.BooleanField(null=True),
        ),
    ]
