# Generated by Django 5.0.3 on 2024-08-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0015_supportticket_details_alter_supportticket_equipament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='company_new_user',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='copy_profile_new_user',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='job_title_new_user',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='machine_new_user',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='mail_tranfer',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='name_new_user',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='old_files',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='sector_new_user',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='software_new_user',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='start_work_new_user',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='where_from',
        ),
    ]
