# Generated by Django 5.0.3 on 2024-12-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipaments',
            fields=[
                ('equipament', models.ImageField(blank=True, null=True, upload_to='equipaments/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.TextField(blank=True, max_length=20, null=True)),
                ('company', models.TextField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
