# Generated by Django 4.2.1 on 2023-10-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipaments',
            name='company',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
